### PR TITLE
Fixed Auto-Join when recording

### LINKED ISSUE #85: Auto Join problem when session is being recorded
Hi,

The scheduler works per described except when the session is being recorded.
When the session is recorded, auto join cannot complete and gets stuck as per screenshot below.
Any suggestion to overcome this?

cannot auto join

### PR DESCRIPTION
**Pull request by 11happy**
Fixed #85

### CODE REVIEW

File: src/scripts/meet.js [hunk 1]
```diff
@@ -1,4 +1,13 @@
+var x = 1;
 setInterval(function () {
+  if(x > 30){
+    console.log('Stopped');
+    clearInterval(this);
+    
+  }
+  else{
+    x++;
+  }
```
Comment (11happy) [inline src/scripts/meet.js:10]: Above code will Stop the script after 4 minutes.

File: src/scripts/meet.js [hunk 2]
```diff
@@ -26,5 +35,14 @@ setInterval(function () {
...
   }
+  try {
+    let join = document.getElementsByClassName(
+      'U26fgb O0WRkf oG5Srb HQ8yf C0oVfc kHssdc HvOprf M9Bg4d'
+    )[0];
+    join.click();
+    console.log('Clicked Join button');
+  } catch (err) {
+    console.log(err);
+  }
```
Comment (11happy) [inline src/scripts/meet.js:46]: Now it can join Recorded meets also.

**Comment by DarshitJain04** [comment]
Lgtm
Next time try to write better commit messages. Here you could have written `added script to auto-join when the session is being recorded`
